spring:
  application:
    name:
      video-platform-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lyl11002211
    url: jdbc:mysql://117.72.70.116:3306/video-platform
  mail:
    host: smtp.qq.com
    username: young.leon@qq.com
    password: xqsrqmupnjgfgcdb
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    port: 456
    protocol: smtp
server:
  port: 8080
  servlet:
    session:
      cookie:
        path: /app
        max - age: 3600
        http - only: true
        name: login_token
    context-path: /app
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      table-underline: false
login-status:
  SECRET_KEY: g9sdf8gy89sdgy9hsdfg789sdgsf907ghsd079gvt324vtvminmi6vt34vt43v
  SALT: 34dvfg6dg76gh78sdgbsd87gadg6sdgsdby458m76m8v4f4356b57bn73
  COOKIE_KEY: login_token
  TOKEN_KEY: userJson
  SERVICE_NAME: video-platform-server