spring:
  application:
    name:
      video-platform-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lyl11002211
    url: jdbc:mysql://117.72.70.116:3306/video-platform?serverTimezone=UTC&useLegacyDatetimeCode=false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5GB
      max-request-size: 5GB
  mail:
    host: smtp.qq.com
    username: 1742181896@qq.com
    password: fxlnsnelwamlbgch
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    port: 465
    protocol: smtp
  data:
    redis:
      database: 1
      port: 6379
      host: 117.72.70.116
  mvc:
    static-path-pattern: /server/**
  web:
    resources:
      static-locations: file:C:/Users/Leon/Desktop/server/
      add-mappings: true
server:
  port: 8081
  servlet:
    session:
      cookie:
        path: /app
        max - age: 3600
        http - only: true
        name: login_token
    context-path: /app
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-underline: false
login-status:
  SECRET_KEY: g9sdf8gy89sdgy9hsdfg789sdgsf907ghsd079gvt324vtvminmi6vt34vt43v
  SALT: 34dvfg6dg76gh78sdgbsd87gadg6sdgsdby458m76m8v4f4356b57bn73
  COOKIE_KEY: login_token
  TOKEN_KEY: userJson
  SERVICE_NAME: video-platform-server